spring:
  thymeleaf:
    cache: false
  freemarker:
    request-context-attribute: request
    suffix: .html
    enabled: true
    charset: utf-8
    settings:
      number_format: '0.##'
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: root
    password: yhjaicly
    driver-class-name: com.mysql.cj.jdbc.Driver

web.upload-path: E:/image
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis/mapper/**/*.xml
